/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/otp`; params?: Router.UnknownInputParams; } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/auth/reset-password`; params?: Router.UnknownInputParams; } | { pathname: `/main/cart`; params?: Router.UnknownInputParams; } | { pathname: `/main/categories`; params?: Router.UnknownInputParams; } | { pathname: `/main/home`; params?: Router.UnknownInputParams; } | { pathname: `/main/orders`; params?: Router.UnknownInputParams; } | { pathname: `/main/product-list`; params?: Router.UnknownInputParams; } | { pathname: `/main/profile`; params?: Router.UnknownInputParams; } | { pathname: `/main/search`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/welcome`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/forgot-password`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/otp`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/register`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/reset-password`; params?: Router.UnknownOutputParams; } | { pathname: `/main/cart`; params?: Router.UnknownOutputParams; } | { pathname: `/main/categories`; params?: Router.UnknownOutputParams; } | { pathname: `/main/home`; params?: Router.UnknownOutputParams; } | { pathname: `/main/orders`; params?: Router.UnknownOutputParams; } | { pathname: `/main/product-list`; params?: Router.UnknownOutputParams; } | { pathname: `/main/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/main/search`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/welcome`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/auth/forgot-password${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | `/auth/otp${`?${string}` | `#${string}` | ''}` | `/auth/register${`?${string}` | `#${string}` | ''}` | `/auth/reset-password${`?${string}` | `#${string}` | ''}` | `/main/cart${`?${string}` | `#${string}` | ''}` | `/main/categories${`?${string}` | `#${string}` | ''}` | `/main/home${`?${string}` | `#${string}` | ''}` | `/main/orders${`?${string}` | `#${string}` | ''}` | `/main/product-list${`?${string}` | `#${string}` | ''}` | `/main/profile${`?${string}` | `#${string}` | ''}` | `/main/search${`?${string}` | `#${string}` | ''}` | `/onboarding/onboarding${`?${string}` | `#${string}` | ''}` | `/onboarding/welcome${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/otp`; params?: Router.UnknownInputParams; } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/auth/reset-password`; params?: Router.UnknownInputParams; } | { pathname: `/main/cart`; params?: Router.UnknownInputParams; } | { pathname: `/main/categories`; params?: Router.UnknownInputParams; } | { pathname: `/main/home`; params?: Router.UnknownInputParams; } | { pathname: `/main/orders`; params?: Router.UnknownInputParams; } | { pathname: `/main/product-list`; params?: Router.UnknownInputParams; } | { pathname: `/main/profile`; params?: Router.UnknownInputParams; } | { pathname: `/main/search`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/welcome`; params?: Router.UnknownInputParams; };
    }
  }
}
